[app]
  # Change this name if it's already taken in Fly.io
  app = "morine-gypsum-backend"
  primary_region = "iad"

[build]
  # Use the included Dockerfile
  image = ""

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1m"
    interval = "15s"
    port = 8080
    restart_limit = 6
